### ISSUE TITLE
Not working correctly in group

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-random-enchants#1]
it wont enchant when an item that is rolled for, you have to pass on it and pick it up, module needs updating to fix this

**Comment by BarbzYHOOL** [comment]
o_0 really?

**Comment by milestorme** [comment]
Yeah this isn’t working at all on any rolled for items

**Comment by Day36512** [comment]
Fixed in my fork: https://github.com/Day36512/mod-random-enchants
