### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by adink1** [azerothcore/mod-random-enchants#15]
/home/ubuntu/azerothcore/modules/mod-random-enchants/src/RandomEnchants.cpp:134:                                                                                                                                                             34: fatal error: no member named 'PQuery' in 'DatabaseWorkerPool<WorldDatabaseCo                                                                                                                                                             nnection>'; did you mean 'Query'?
                QueryResult qr = WorldDatabase.PQuery("SELECT enchantID FROM ite                                                                                                                                                             m_enchantment_random_tiers WHERE tier='%d' AND exclusiveSubClass=NULL AND class=                                                                                                                                                             '%s' OR exclusiveSubClass='%u' OR class='ANY' ORDER BY RAND() LIMIT 1", tier, Cl                                                                                                                                                             assQueryString.c_str(), item->GetTemplate()->SubClass);
                                               ^~~~~~
                                               Query
/home/ubuntu/azerothcore/src/server/database/Database/DatabaseWorkerPool.h:119:1                                                                                                                                                             7: note: 'Query' declared here
    QueryResult Query(std::string_view sql, Args&&... args)
                ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:1532: modules/CMakeFiles                                                                                                                                                             /modules.dir/mod-random-enchants/src/RandomEnchants.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by Winfidonarleyan** [comment]
> `QueryResult qr = WorldDatabase.PQuery("SELECT enchantID FROM ite m_enchantment_random_tiers WHERE tier='%d' AND exclusiveSubClass=NULL AND class= '%s' OR exclusiveSubClass='%u' OR class='ANY' ORDER BY RAND() LIMIT 1", tier, Cl assQueryString.c_str(), item->GetTemplate()->SubClass);` remplace by: `QueryResult qr = WorldDatabase.Query("SELECT enchantID FROM ite m_enchantment_random_tiers WHERE tier='%d' AND exclusiveSubClass=NULL AND class= '%s' OR exclusiveSubClass='%u' OR class='ANY' ORDER BY RAND() LIMIT 1", tier, Cl assQueryString.c_str(), item->GetTemplate()->SubClass);`

no, need use new fmt
