### ISSUE TITLE
Cannot be compiled

### ISSUE THREAD

**Issue by ninjaskija** [azerothcore/mod-random-enchants#7]
I have the following warning when trying to compile with the azerothcore commit `ce8db43`

`RandomEnchants.cpp:37:20: fatal error: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
                if ((Quality > 5 && Quality < 1)/*eliminates enchanting anything that isn't a recognized quality*/ || (Class != 2 && Class != 4)/*eliminates enchanting anything but weapons/armor*/)
                     ~~~~~~~~~~~~^~~~~~~~~~~~~~`

**Comment by Helias** [comment]
it's just a warning easy to fix, give me 5 mins

**Comment by Helias** [comment]
Fixed by https://github.com/azerothcore/mod-random-enchants/commit/39aefca0f768862991df0bb1661eddaa99b965f2
Thank you for the report.
